---
title: "Análisis de Varianza - ANOVA"
output:
  html_document:
    css: !expr here::here("styles/styles.css")
    toc: true
    toc_depth:  3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options("yaml.eval.expr" = TRUE)
```

# 3.1.Análisis de Varianza  
> Inferencias sobre las medias de varias poblaciones   

En el tema anterior estuvimos haciendo comparaciones de medias entre dos muestras; frecuentemente, sin embargo, necesitamos comparar las medias de más de dos muestras.  La metodología estadística utilizada comúnmente para estos casos, es el __análisis de varianza__ (ANOVA).

El análisis de varianza es la herramienta usualmente utilizada cuando queremos analizar el efecto de diferentes __grupos__ (una variable categórica) en una variable medida (__respuesta__).  La técnica del ANOVA es útil tanto para __diseños experimentales__, como para __observaciones__ o __encuestas__.  La hipótesis nula para este tipo de análisis, para el caso de que tengamos tres grupos, es usualmente:  
$$H_0 : \mu_A = \mu_B = \mu_C$$
Ahora bien, podemos preguntarnos por qué no usamos múltiples pruebas _t_, y descomponemos la hipótesis anterior en tres hipótesis nulas.  En primer lugar, no es práctico si tenemos muchos grupos.  Por ejemplo, con cuatro grupos, usando la fórmula de combinaciones, tendríamos seis parejas de $H_0$ para probar, con ocho grupos tendríamos ¡28!  En segundo lugar, al realizar múltiples pruebas _t_ el __error tipo I__ se va incrementando al aumentar el número de pruebas.  El ANOVA supera ambos problemas.  

## 3.1.1.Fundamentos y Supuestos del ANOVA  
#### Objetivos  
__Conocer los fundamentos teóricos y supuestos para realizar el análisis de varianza__  

Tenemos el siguiente modelo para describir el valor de cualquier observación, proveniente de varios grupos ($n_i, i=1...k$), cada uno con $n_{ij}$ observaciones:  
$$y_{ij} = \mu + \alpha_i + e_{ij}$$



[  __Home__](https://dsfernandez.github.io/bioestadisticas/index.html)

## 3.1.2.ANOVA de Una Vía con Efectos Fijos



[  __Home__](https://dsfernandez.github.io/bioestadisticas/index.html)

## 3.1.3.Comparaciones Múltiples



[  __Home__](https://dsfernandez.github.io/bioestadisticas/index.html)

## 3.1.4.Supuestos para el ANOVA y Remedios

 

[  __Home__](https://dsfernandez.github.io/bioestadisticas/index.html)

## 3.1.5.Otros Diseños de ANOVA

efectos aleatorios
ANOVA con dos factores
ANOVA con repeticiones
ANCOVA
 

[  __Home__](https://dsfernandez.github.io/bioestadisticas/index.html)

